services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - 5432:5432
  valkey:
    image: "valkey/valkey:8"
    ports:
    - "6379:6379"
